services:
  vendingmachine:
    image: vendingmachine
    build:
      context: ./backend
      dockerfile: VendingMachine.API/Dockerfile
    networks:
      vending-machine-network:
        aliases:
          - backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vending-machine-network
    depends_on:
      - vendingmachine

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: VendingMachine
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - vending-machine-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  vending-machine-network:
    
volumes:
  postgres:
